# Example secrets file - DO NOT commit actual credentials
# Use kubectl create secret or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: oz-monitor-orchestrator
type: Opaque
stringData:
  url: "postgresql://monitor_user:changeme@postgres.stellar-monitor.svc.cluster.local:5432/tenant_isolation"
---
apiVersion: v1
kind: Secret
metadata:
  name: rpc-endpoints
  namespace: oz-monitor-orchestrator
type: Opaque
stringData:
  ethereum: "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
  polygon: "https://polygon-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
  stellar: "https://horizon.stellar.org"